import { GrblSetting } from '../types/cnc';

export const DEFAULT_GRBL_SETTINGS: GrblSetting[] = [
  {
    id: '$0',
    code: 0,
    name: 'Step pulse time',
    description: 'Schrittimpulsdauer in Mikrosekunden (min 3us)',
    unit: 'microseconds',
    category: 'Steps',
    value: '10',
    defaultValue: '10',
  },
  {
    id: '$1',
    code: 1,
    name: 'Step idle delay',
    description: 'Schrittmotor-Haltestromverzögerung (255 = Motoren bleiben immer bestromt)',
    unit: 'milliseconds',
    category: 'Steps',
    value: '255',
    defaultValue: '25',
  },
  {
    id: '$2',
    code: 2,
    name: 'Step pulse invert',
    description: 'Schrittimpuls-Invertierungsmaske (Bitmaske für X, Y, Z)',
    unit: 'mask',
    category: 'Inversion',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$3',
    code: 3,
    name: 'Step direction invert',
    description: 'Richtungsinvertierungsmaske (Bitmaske: X=1, Y=2, Z=4)',
    unit: 'mask',
    category: 'Inversion',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$4',
    code: 4,
    name: 'Invert step enable pin',
    description: 'Enable-Signal invertieren (0=Low aktiv, 1=High aktiv)',
    unit: 'boolean',
    category: 'Inversion',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$5',
    code: 5,
    name: 'Invert limit pins',
    description: 'Endschalter-Eingänge invertieren (0=Normally Open, 1=Normally Closed)',
    unit: 'boolean',
    category: 'Inversion',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$6',
    code: 6,
    name: 'Invert probe pin',
    description: 'Taster-Signal invertieren (0=Low aktiv, 1=High aktiv)',
    unit: 'boolean',
    category: 'Inversion',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$10',
    code: 10,
    name: 'Status report options',
    description: 'Statusbericht-Maske (WPos vs MPos, Bufferdaten, Pins)',
    unit: 'mask',
    category: 'General',
    value: '1',
    defaultValue: '1',
  },
  {
    id: '$11',
    code: 11,
    name: 'Junction deviation',
    description: 'Bahnübergangsabweichung für Kurvengeschwindigkeit',
    unit: 'mm',
    category: 'Speeds & Accel',
    value: '0.010',
    defaultValue: '0.010',
  },
  {
    id: '$12',
    code: 12,
    name: 'Arc tolerance',
    description: 'Bogenannäherungstoleranz (G2/G3 Glättung)',
    unit: 'mm',
    category: 'Speeds & Accel',
    value: '0.002',
    defaultValue: '0.002',
  },
  {
    id: '$13',
    code: 13,
    name: 'Report in inches',
    description: 'Statusberichte in Zoll statt Millimeter ausgeben',
    unit: 'boolean',
    category: 'General',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$20',
    code: 20,
    name: 'Soft limits enable',
    description: 'Software-Endschalter aktivieren (erfordert Homing)',
    unit: 'boolean',
    category: 'Limits & Homing',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$21',
    code: 21,
    name: 'Hard limits enable',
    description: 'Hardware-Endschalter-Überwachung aktivieren',
    unit: 'boolean',
    category: 'Limits & Homing',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$22',
    code: 22,
    name: 'Homing cycle enable',
    description: 'Referenzfahrt-Zyklus ($H) aktivieren',
    unit: 'boolean',
    category: 'Limits & Homing',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$23',
    code: 23,
    name: 'Homing direction invert',
    description: 'Suchrichtung der Referenzfahrt invertieren',
    unit: 'mask',
    category: 'Limits & Homing',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$24',
    code: 24,
    name: 'Homing feed rate',
    description: 'Langsame Suchgeschwindigkeit beim Antasten des Schalters',
    unit: 'mm/min',
    category: 'Limits & Homing',
    value: '25.000',
    defaultValue: '25.000',
  },
  {
    id: '$25',
    code: 25,
    name: 'Homing seek rate',
    description: 'Schnelle Suchgeschwindigkeit zur Schalterannäherung',
    unit: 'mm/min',
    category: 'Limits & Homing',
    value: '500.000',
    defaultValue: '500.000',
  },
  {
    id: '$26',
    code: 26,
    name: 'Homing switch debounce delay',
    description: 'Schalter-Entprellzeit in Millisekunden',
    unit: 'milliseconds',
    category: 'Limits & Homing',
    value: '250',
    defaultValue: '250',
  },
  {
    id: '$27',
    code: 27,
    name: 'Homing pull-off distance',
    description: 'Rückzugsabstand vom Endschalter nach Referenzierung',
    unit: 'mm',
    category: 'Limits & Homing',
    value: '1.000',
    defaultValue: '1.000',
  },
  {
    id: '$30',
    code: 30,
    name: 'Maximum spindle speed',
    description: 'Maximale Spindeldrehzahl / Servo-PWM (M3 Smax)',
    unit: 'RPM / PWM',
    category: 'Spindle / Laser',
    value: '1000',
    defaultValue: '1000',
  },
  {
    id: '$31',
    code: 31,
    name: 'Minimum spindle speed',
    description: 'Minimale Spindeldrehzahl / Servo-PWM (M3 Smin)',
    unit: 'RPM / PWM',
    category: 'Spindle / Laser',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$32',
    code: 32,
    name: 'Laser-mode enable',
    description: 'Laser-Modus (1=Laser mit dynamischer Leistung M4, 0=Stift/Spindel)',
    unit: 'boolean',
    category: 'Spindle / Laser',
    value: '0',
    defaultValue: '0',
  },
  {
    id: '$100',
    code: 100,
    name: 'X-axis travel resolution',
    description: 'Schritte pro Millimeter für X-Achse',
    unit: 'steps/mm',
    category: 'Steps',
    value: '80.000',
    defaultValue: '80.000',
  },
  {
    id: '$101',
    code: 101,
    name: 'Y-axis travel resolution',
    description: 'Schritte pro Millimeter für Y-Achse',
    unit: 'steps/mm',
    category: 'Steps',
    value: '80.000',
    defaultValue: '80.000',
  },
  {
    id: '$102',
    code: 102,
    name: 'Z-axis travel resolution',
    description: 'Schritte pro Millimeter für Z-Achse',
    unit: 'steps/mm',
    category: 'Steps',
    value: '400.000',
    defaultValue: '400.000',
  },
  {
    id: '$110',
    code: 110,
    name: 'X-axis maximum rate',
    description: 'Maximale Eilgang-Geschwindigkeit der X-Achse (G0)',
    unit: 'mm/min',
    category: 'Speeds & Accel',
    value: '3000.000',
    defaultValue: '3000.000',
  },
  {
    id: '$111',
    code: 111,
    name: 'Y-axis maximum rate',
    description: 'Maximale Eilgang-Geschwindigkeit der Y-Achse (G0)',
    unit: 'mm/min',
    category: 'Speeds & Accel',
    value: '3000.000',
    defaultValue: '3000.000',
  },
  {
    id: '$112',
    code: 112,
    name: 'Z-axis maximum rate',
    description: 'Maximale Eilgang-Geschwindigkeit der Z-Achse (G0)',
    unit: 'mm/min',
    category: 'Speeds & Accel',
    value: '1000.000',
    defaultValue: '1000.000',
  },
  {
    id: '$120',
    code: 120,
    name: 'X-axis acceleration',
    description: 'Beschleunigung der X-Achse',
    unit: 'mm/sec²',
    category: 'Speeds & Accel',
    value: '200.000',
    defaultValue: '200.000',
  },
  {
    id: '$121',
    code: 121,
    name: 'Y-axis acceleration',
    description: 'Beschleunigung der Y-Achse',
    unit: 'mm/sec²',
    category: 'Speeds & Accel',
    value: '200.000',
    defaultValue: '200.000',
  },
  {
    id: '$122',
    code: 122,
    name: 'Z-axis acceleration',
    description: 'Beschleunigung der Z-Achse',
    unit: 'mm/sec²',
    category: 'Speeds & Accel',
    value: '100.000',
    defaultValue: '100.000',
  },
  {
    id: '$130',
    code: 130,
    name: 'X-axis maximum travel',
    description: 'Maximaler Verfahrweg der X-Achse (Arbeitsbereich)',
    unit: 'mm',
    category: 'Limits & Homing',
    value: '300.000',
    defaultValue: '300.000',
  },
  {
    id: '$131',
    code: 131,
    name: 'Y-axis maximum travel',
    description: 'Maximaler Verfahrweg der Y-Achse (Arbeitsbereich)',
    unit: 'mm',
    category: 'Limits & Homing',
    value: '200.000',
    defaultValue: '200.000',
  },
  {
    id: '$132',
    code: 132,
    name: 'Z-axis maximum travel',
    description: 'Maximaler Verfahrweg der Z-Achse (Arbeitsbereich)',
    unit: 'mm',
    category: 'Limits & Homing',
    value: '50.000',
    defaultValue: '50.000',
  },
];
